### ISSUE TITLE
toonloop is way too slow on GM965/GL960 Intel video cards

### ISSUE THREAD

**Issue by spiette** [aalex/toonloop#5]
How to reproduce (on an Intel 96x chipset video card):
1) Get the .deb or compile the latest git source
2) Install toonloop -v
3) Cry to see lower than 1fps and have an unusable nice piece of software

What's expected:
30fps on any recent hardware

**Comment by aalex** [comment]
Which camera are you using? Try increasing the lighting, so that the frame rate might increase as well. 

You could try the Clutter toys or some Clutter games to compare the performance. Since Toonloop 2.0 doesn't use any shader yet, I think it's probably not the video card that is the culprit.

**Comment by spiette** [comment]
Ah, libclutter is the culprit. Found out that using 
    export CLUTTER_VBLANK=none
will work.
Bug described here: https://bugs.launchpad.net/ubuntu/lucid/+source/clutter-1.0/+bug/572465

Now I can make faces! : )
